### ISSUE TITLE
Cannot set username and access key from the CLI

### ISSUE THREAD

**Issue by tim-vyg** [LambdaTest/lambdatest-cypress-cli#235]
Seems to force `lambdatest_auth` in config file but documentation says you can set from the command line

https://www.lambdatest.com/support/docs/authentication/

**Comment by 4DvAnCeBoY** [comment]
@tim-vyg Please refer to this section, You can remove the lambdatest_auth block from the config json file.
https://www.lambdatest.com/support/docs/getting-started-with-cypress-testing/

**Comment by tim-vyg** [comment]
When I do and insert into CLI - it says username is `undefined`

**Comment by HRanjan-11** [comment]
@tim-vyg if you keep this empty in lambdatest config file 
"lambdatest_auth": {
   
  },
  
  and then pass the username through cli. it will pick the username from cli. 

  but generally without doing the above, passing username in cli should have worked. it will be fixed in the next release of cli.

**Comment by HRanjan-11** [comment]
this has been released in the latest cli version. 
https://www.npmjs.com/package/lambdatest-cypress-cli/v/3.0.26

Closing this issue.
