### ISSUE TITLE
Option to run in Headed mode

### ISSUE THREAD

**Issue by kmcid** [LambdaTest/lambdatest-cypress-cli#55]
My runs from Cypress v8 runs tests in headless by default, I am interested in the recorded video provided by lambdatest.
Is there a way to disable this default behaviour? I can't find a way to configure this using cli.
`Cypress:    8.3.1
Browser:    Custom Chrome 93 (headless)`

Tried the kitchensink example which uses an older version of cypress, the chrome run is headed.
`Cypress:    6.2.1  
Browser:    Custom Chrome 93`

**Comment by asad9711** [comment]
@kmcid For recording video for a test, you don't need to pass any configuration parameter via cli. If the tests ran successfully, then the recorded video must be available on your lambdatest dashboard

**Comment by kmcid** [comment]
Yes @asad9711, I do see the recorded video, but the browser does not display in the video because cypress runs in headless by default.

**Comment by asad9711** [comment]
@kmcid I am referring your issue to our customer support team. They will be helping you resolve your concerns

**Comment by asad9711** [comment]
@kmcid We have added the support to choose headless/headed option for the test.
You can try it by installing latest lambdatest-cypress-cli https://www.npmjs.com/package/lambdatest-cypress-cli/v/2.0.9

In order to run headless, you can pass `--headless` in lambdatest run command
OR in `lambdatest-config.json` file, inside`run_settings` as `"headless": true`
